### ISSUE TITLE
FPS Limit

### ISSUE THREAD

**Issue by aiuser** [n00mkrad/flowframes#1]
Is there a limit for maximum FPS that can be created? It seems it can't go higher then 400 or 500 fps, saying "Invalid target frame rate". Might it be because input fps is something like 240,006 ?

**Comment by n00mkrad** [comment]
There is a hard limit of 480 FPS (in v15) or 500 FPS (in the upcoming update). This is for compatibility reasons, and I honestly can't see why you'd want a video above 500 FPS.

**Comment by aiuser** [comment]
There is camera's that can do 10000 fps, so why not?

**Comment by n00mkrad** [comment]
Mostly because I can't guarantee that encoding and playback works well beyond 500 FPS.

I will make it a config option in the future so users can remove the limit if they want to.

**Comment by aiuser** [comment]
Thank you)
