### ISSUE TITLE
Output to "Image Sequence" ignores "Output Directory"

### ISSUE THREAD

**Issue by BestUsername** [n00mkrad/flowframes#10]
To reproduce
Version: V17-RC4

Package Installer:

- RIFE (Nvidia)
- Python Runtime
- Audio/Video Tools
- Licenses

Interpolation settings:
- Interpolation AI: RIFE - CUDA/Pytorch Implementation of RIFE
- Input Video: C:\Users\USER\Desktop\run(image sequence of 8 frames)
- Output Directory: C:\Users\USER\Desktop\run\images (exists and is empty)
- Set FPS: input-12, x2, = 24 Ouput FPS
- Tile Size - Not available for selected AI
- Output Mode: Image Sequence

Expected outcome: output images get written in the "Output Directory"
Actual outcome: output images get written to C:\Users\USER\Desktop\run-interpolated

Log panel output:

Welcome to Flowframes!
This is the console output box. Status messages will appear here.
Flowframes is up to date.
Failed to detect drive type: Could not detect Disk Id of H
Video FPS (Loaded from fps.ini): Not Found - Total Number Of Frames: 8
Input Resolution: 150x200
Importing images...
Generating timecodes... Done.
Using embedded Python runtime.
Running RIFE (interp-parallel.py)...
Interpolated 15/18 frames (83%) - Average Speed: 3.35 FPS In / 6.69 FPS Out - Time: 05s - ETA: 0ms
Done running RIFE - Interpolation took 05s
Moving interpolated frames out of temp folder...
C:\Users\USER\Desktop\run-temp\interp -> C:\Users\USER\Desktop\run-interpolated
Deleting temporary files...
Total processing time: 05s

**Comment by n00mkrad** [comment]
Fixed in 1.19.0
