### ISSUE TITLE
bug reports

### ISSUE THREAD

**Issue by adivvkvns** [n00mkrad/flowframes#101]
Hello. In FlowFrames 1.32.0, when choosing a RIFE - Cuda/Pytorch AI model, there I get an error.
Well i have a NVIDIA GeForce GT 730M dGPU 1GB DDR3 

in my laptop.
Maybe I have an unsupported GPU, but why can't it just work? Is there any justification?

[rife-cuda-log.txt](https://docs.google.com/document/d/1i2591V8k-on3Cdk0O0WktFJ0lIlNv5mGuHbqvQKedfI/edit?usp=sharing)

![CcuG95b7nM0](https://user-images.githubusercontent.com/97660050/149334920-c1e129e7-524b-4b68-a90f-047cc99889d4.jpg)
![sBTmDzWF1wg](https://user-images.githubusercontent.com/97660050/149335702-a9e62080-5a82-4550-ba76-ce2785ee9874.jpg)

**Comment by banjaminicc** [comment]
There are simply functions that require a higher CUDA version to perform
So yes it is justified

**Comment by adivvkvns** [comment]
> There are simply functions that require a higher CUDA version to perform So yes it is justified

God damn, that sucks👺👺👺

But it works great through the RIFE (NCNN) Vulkan and half precision (CUDA) setting enabled anyways 😁
Thanx
