### ISSUE TITLE
Bug: Multiple GPU Support not working

### ISSUE THREAD

**Issue by MattieX** [n00mkrad/flowframes#11]
I cannot get the Multiple GPU support working, however they work on both cards individually when specifying their Pytorch ID (0 or 1).
The interpolation process will still work with both ID's, it will just pick the first GPU ID entered in the Pytorch GPU IDs section and use that GPU exclusively for the process.

![image](https://user-images.githubusercontent.com/21284075/105396709-1d91d880-5c18-11eb-9409-07d32a721dcd.png)

**GPU's:**
RTX 3080
GTX 1080
**Interpolation Method**
RIFE - CUDA
**Output Method**
Image Sequence or MP4
**Prerequisites**
I am using System Python as I cannot see the Rtx-3000 Pkg Folder on the Itch download for the latest version.
Using all the listed recommended versions of Python and Python Modules that this Github page recommends.
**Releases Tested On**
1.20.4 - Self Built
1.19.1 - Latest Itch Release

When turning on the CMD debugging option, release 1.19.1 clearly detects the presence of both GPU's but when the process begins however it only goes onto use 1 - please see attached screenshots. My self built version does not print this same message to the console, however the same behaviour is observed.

![image](https://user-images.githubusercontent.com/21284075/105396360-b3793380-5c17-11eb-8f78-401f6065baff.png)
![image](https://user-images.githubusercontent.com/21284075/105396390-be33c880-5c17-11eb-93b6-a6e82d0284a2.png)

**Comment by n00mkrad** [comment]
Multi-GPU for CUDA is currently not implemented, but planned for the future.

Also, update your CuDNN to 8005.
Your current version severly decreases your performance.

**Comment by MattieX** [comment]
> Multi-GPU for CUDA is currently not implemented, but planned for the future.
> NCNN multi-GPU works, but is probably slower than CUDA on a single GPU.
> 
> Also, update your CuDNN to 8005.
> Your current version severly decreases your performance.

Thanks for your reply, looking forward to the Cuda multi-GPU support in the future!
I've followed the steps here [](url

**Comment by Katzenwerfer** [comment]
> I've followed the steps here [https://docs.nvidia.com/deeplearning/cudnn/install-guide/index.html#install-windows](url) for Windows, however unfortunately the program still seems to say version 8004. Any tips? For reference I'm using cudnn-10.2-windows10-x64-v8.0.5.39 to match the PyTorch CU version.

The current version is packed on 3 ways: _Full, Full-3000 and slim_
the full-3000 one is compatible with the 3080 and has the updated cudnn

**Comment by MattieX** [comment]
> > I've followed the steps here [https://docs.nvidia.com/deeplearning/cudnn/install-guide/index.html#install-windows](url) for Windows, however unfortunately the program still seems to say version 8004. Any tips? For reference I'm using cudnn-10.2-windows10-x64-v8.0.5.39 to match the PyTorch CU version.
> 
> The current version is packed on 3 ways: _Full, Full-3000 and slim_
> the full-3000 one is compatible with the 3080 and has the updated cudnn

Thanks for doing that - greatly appreciated!

**Comment by n00mkrad** [comment]
Closing for now.

To recap the original issue:
Multi-GPU is currently only supported with RIFE-NCNN.
RIFE-CUDA support is planned for the near future.
