### ISSUE TITLE
vkAllocateMemory Faied -2

### ISSUE THREAD

**Issue by DDXDB** [n00mkrad/flowframes#12]
I have three GPUs

I'll say "VKALLOCatememory FAIED-2" when I run it

GPU2 also has no utilization

Set as shown in figure
![2021-01-27 (1)](https://user-images.githubusercontent.com/38449595/105955173-d5a80100-60b0-11eb-8fd2-488d9df629d4.png)
![2021-01-27](https://user-images.githubusercontent.com/38449595/105955177-d6409780-60b0-11eb-9ee9-a1eff941fb37.png)

**Comment by Katzenwerfer** [comment]
I'm pretty sure that's an out of memory error
that or you were using too much ncnn threads

**Comment by DDXDB** [comment]
> I'm pretty sure that's an out of memory error
> that or you were using too much ncnn threads

I have 16GB of RAM

NCNN to 1

**Comment by n00mkrad** [comment]
> > I'm pretty sure that's an out of memory error
> > that or you were using too much ncnn threads
> 
> I have 16GB of RAM
> 
> NCNN to 1

GPU VRAM is what matters. 

Makre sure it's running on the 5500 XT, the others don't have enough VRAM for 4K.

**Comment by DDXDB** [comment]
My 5500XT has 8GB of VRAM

The other R9 270X has 2GB of VRAM

But the error still

**Comment by YiWeiHuang-stack** [comment]
I think 8G VRAM is not enough to use RIFE-NCNN to interpolate 4K video

**Comment by XDM-Inc** [comment]
i have a 3090 with TWENTYFOUR GIGS of vram and it keeps telling me that a 1mb 1 second video is too much for my gpu?? no way in hell is that true!

**Comment by n00mkrad** [comment]
> i have a 3090 with TWENTYFOUR GIGS of vram and it keeps telling me that a 1mb 1 second video is too much for my gpu?? no way in hell is that true!

Why not use RIFE CUDA

**Comment by XDM-Inc** [comment]
> > i have a 3090 with TWENTYFOUR GIGS of vram and it keeps telling me that a 1mb 1 second video is too much for my gpu?? no way in hell is that true!
> 
> Why not use RIFE CUDA

that's what i do, that works just fine but anything Cuda related on my pc is just bad, even my topaz ai stuff is acting stupid with a similar error

**Comment by Katzenwerfer** [comment]
Bad in which way?
Usually overclocking can cause issues with the program. If you have any, disabling it might be worth a try.

**Comment by madhatr** [comment]
I am getting this issue as well with a GTX 1080 Ti, it has 11GB a vram.   Sometimes it says there is not enough vram to start othertimes it starts but fails mid way.

**Comment by XDM-Inc** [comment]
Also i have a POSSIBLE work around ( if it's falsely reporting you don't have enough vram.)
Go to device manager and disable your graphics card then re enable it. It has a SMALL chance of working. (This clears the cuda and vram usage

**Comment by madhatr** [comment]
I think the same thing can be accomplished with WIN+CTRL+SHIFT+B,  it is a win hot key to reset video driver.

**Comment by XDM-Inc** [comment]
> I think the same thing can be accomplished with WIN+CTRL+SHIFT+B, it is a win hot key to reset video driver.

wow.... in all my computing years why id this the FIRST time I've head of this wonderful shortcut?? thanks for that
