### ISSUE TITLE
Switch to Win32_VideoController instead of Win32_DisplayConfiguration in the GetGpus function?

### ISSUE THREAD

**Issue by DrPleaseRespect** [n00mkrad/flowframes#126]
I have an NVIDIA Optimus Computer and the Flowframes can detect my NVIDIA GPU although the GetGpus function only gets my Intel iGPU.

I also double checked it using "get-wmiobject Win32_DisplayConfiguration" (in powershell)
and that also only got my iGPU.

I tried replacing 
``ManagementObjectSearcher searcher = new ManagementObjectSearcher("SELECT * FROM Win32_DisplayConfiguration");`` 
to 
``ManagementObjectSearcher searcher = new ManagementObjectSearcher("SELECT * FROM Win32_VideoController");``
and now it's able to detect my NVIDIA GPU

Win32_VideoController: https://docs.microsoft.com/en-us/windows/win32/cimwin32prov/win32-videocontroller
![Flowframes_5IV8iDUZIp](https://user-images.githubusercontent.com/61642760/156411504-bacec3aa-08b7-4358-8e52-13b9cae35914.png)
![Flowframes_A8lkBuvkju](https://user-images.githubusercontent.com/61642760/156411529-f004a096-781b-445e-82de-1d0f6c89b5d4.png)

**Comment by n00mkrad** [comment]
Done
