### ISSUE TITLE
Failed to open video "frame extraction failed"

### ISSUE THREAD

**Issue by HackerDaGreat57** [n00mkrad/flowframes#132]
Whenever I open up Flowframes and try to interpolate **any** kind of video - mp4, mkv, gif, etc - it always gives me this error. Even the samples are failing.
![image](https://user-images.githubusercontent.com/70416002/163701493-a9a70561-fcd6-4583-8530-0597b9005cf3.png)

I'm using RIFE-4.0 model.

**Comment by HackerDaGreat57** [comment]
Nevermind. Disabling command prompt in the settings fixed it.

**Comment by dxslayerua** [comment]
I don’t really understand what command line you’re talking about

**Comment by dxslayerua** [comment]
![изображение_2024-07-15_213452569](https://github.com/user-attachments/assets/2336aecb-a2eb-46e4-87c1-bf447fa8e7a0)

**Comment by Spaqi** [comment]
I cant find the command prompt in flowframes can u help ?
