### ISSUE TITLE
Canceled interpolation failed

### ISSUE THREAD

**Issue by dumpleboi** [n00mkrad/flowframes#136]
![interpolation](https://user-images.githubusercontent.com/104884024/166625683-8ce39580-9d96-413f-943e-1da1de0afa63.png)

Hello, I just downloaded this program and wanted to experiment with it using a few png frames, but every time I try to interpolate it, I receive this message. I tried to changed it to jpg, mess around with the setting of Flowframes but nothing. I'm not sure why it's not working. I'm using a lenovo laptop with a Intel (R) HD graphics 520.

**Comment by DrPleaseRespect** [comment]
GPU could be too weak

**Comment by Tsubajashi** [comment]
gpu unsupported.

**Comment by Exey** [comment]
3090 not supported?
