### ISSUE TITLE
Is Software only support NVIDIA Graphics Card? 

### ISSUE THREAD

**Issue by AkarinLiu** [n00mkrad/flowframes#144]
I want to try this software, but I don't know if AMD graphics and NVIDIA graphics are supported.

**Comment by DrPleaseRespect** [comment]
CUDA only works for NVIDIA
But NCNN is also Available and is supported by most Graphics Cards

**Comment by AkarinLiu** [comment]
Thanks



发自我的小米手机
在 DrPleaseRespect ***@***.***>，2022年5月25日 14:14写道：

CUDA only works for NVIDIA
But NCNN is also Available and is supported by most Graphics Cards
