### ISSUE TITLE
DAIN (Missing Index File)

### ISSUE THREAD

**Issue by Animeke** [n00mkrad/flowframes#146]
When I try to use DAIN, before it starts interpolating I get an error of a missing index. Anyone know why?

**Comment by n00mkrad** [comment]
Have you tried again? Works on my end.

**Comment by NoticeableScout121** [comment]
I've tried it again, still getting the same error. I've switched to RIFE for now which I'll probably keep using.
![Image](https://user-images.githubusercontent.com/38185410/172263274-74f76f0f-449d-4a74-aa52-cee0fd15cedd.PNG)

**Comment by NoticeableScout121** [comment]
I've tried it again, still getting the same error. I've switched to RIFE for now which I'll probably keep using.
![Capture](https://user-images.githubusercontent.com/38185410/172263969-62c82760-e55f-4b76-afd2-7c29559e0100.PNG)

**Comment by AugmentedRealityCat** [comment]
I found a solution to make DAIN work, look in this thread:
https://github.com/n00mkrad/flowframes/issues/98#issuecomment-1287898709 

Basically, you have to download another version of files.json from another server, and then you have to replace the dummy files it will download with the real ones from the DAIN official release.

I hope it will work for you as well.
