### ISSUE TITLE
Canceled interpolation failed with Radeon RX 590?

### ISSUE THREAD

**Issue by twy0622** [n00mkrad/flowframes#154]
![Untitled](https://user-images.githubusercontent.com/73870194/174454763-30933177-37df-4d55-8d7b-7b6b895d0114.png)
I looked up similar error messages and apparently its gpu unsupported
Am I doing something wrong or is the Sapphire Nitro+ RX590 not supported for Flowframes.
Perhaps I disabled something that has made it stop working.
Any help is appreciated. Thanks.

Running AMD Adrenalin Version 22.5.2

**Comment by n00mkrad** [comment]
Try rolling back your drivers

**Comment by ssghizh** [comment]
> ![Untitled](https://user-images.githubusercontent.com/73870194/174454763-30933177-37df-4d55-8d7b-7b6b895d0114.png) I looked up similar error messages and apparently its gpu unsupported Am I doing something wrong or is the Sapphire Nitro+ RX590 not supported for Flowframes. Perhaps I disabled something that has made it stop working. Any help is appreciated. Thanks.
> 
> Running AMD Adrenalin Version 22.5.2
I got the 5500xt and have successfully used flowframes before but now i get the same error message, I think its an issue with the newest drivers

**Comment by twy0622** [comment]
I rolled back to 22.3.2 and this time it resulted in the driver timing out three times before giving the same error messages. I do recall being able to use flowframes 6-12 months back.

**Comment by twy0622** [comment]
works on amd latest driver update 22.6.1
