### ISSUE TITLE
When using AMD, Flowframes takes too long to interpolate

### ISSUE THREAD

**Issue by CrackDISSIIEE** [n00mkrad/flowframes#159]
I have an AMD Radeon 580X Series, I was using DAIN NCNN because I would like more specific frames. Interpolating took HORRENDOUSLY long. For a clip that was a few frames long, it said I would have to wait 30 minutes. My friend with an NVIDIA card says the same clip took 20 seconds to interpolate for him. I used RIFE NCNN because I did not want to wait 30 minutes, it took a minute but I didn't have the same variety of frames I would have gotten if I used DAIN. Is there any way to fix this issue?

**Comment by snoopchallenge** [comment]
But why use dain when the arxiv paper for rife shows it has better results

**Comment by n00mkrad** [comment]
> I have an AMD Radeon 580X Series, I was using DAIN NCNN because I would like more specific frames. Interpolating took HORRENDOUSLY long. For a clip that was a few frames long, it said I would have to wait 30 minutes. My friend with an NVIDIA card says the same clip took 20 seconds to interpolate for him. I used RIFE NCNN because I did not want to wait 30 minutes, it took a minute but I didn't have the same variety of frames I would have gotten if I used DAIN. Is there any way to fix this issue?

Use RIFE.

DAIN is outdated and it's only included in Flowframes for the sake of it being there.
