### ISSUE TITLE
Stuck at the "Waiting for encoding to finish..." 

### ISSUE THREAD

**Issue by huseyinekrem** [n00mkrad/flowframes#16]
If I disable Remove Dublicated frames, encoder never finish the video. 

version: 1.20.4
Dain NCNN - Vulkan
RX 570 GPU

**Comment by n00mkrad** [comment]
Fixed in 1.21.

Disable auto-encode in the meantime.

**Comment by noobtoob4lyfe** [comment]
same issue with 1.36.1 for me.

**Comment by eddyyxxyy** [comment]
Im with the same problem, what can I do?

**Comment by DuckersMcQuack** [comment]
Same issue for me 2 years later.
