### ISSUE TITLE
Command line call: "-factor=X" argument not working

### ISSUE THREAD

**Issue by 4c30** [n00mkrad/flowframes#162]
Hello, i was writing a script that automates FlowFrames to use custom settings based on the fps of the input video,
So i found this [github issue](https://github.com/n00mkrad/flowframes/issues/67) that explained how to use the CLI

However when called from the command line, FlowFrames ignores the -factor parameter and **defaults to 2x**

i have tried `-factor=4` and  `-factor=8` but it doesn't work
Some commands i have tried:
`flowframes INPUT -factor=4 -start -quit-when-done`
`flowframes INPUT -factor=4 -ai=1 -model=5 -start -quit-when-done`
`flowframes INPUT -factor=4 -ai=0`
`flowframes INPUT -factor=4 -ai=2`

Also, since RIFE-NCNN now supports fractional factors, would it be possible to add support for it from the command line?

Thanks in advance

**Comment by n00mkrad** [comment]
Huh that's weird, will check

**Comment by n00mkrad** [comment]
Fixed https://github.com/n00mkrad/flowframes/commit/8c918c370b04f44e850323c6990c8649d1451f7e
