### ISSUE TITLE
VapourSynth not starting at all

### ISSUE THREAD

**Issue by sabaasa** [n00mkrad/flowframes#165]
![Screenshot_26](https://user-images.githubusercontent.com/75037904/178336350-f1a8384a-469a-4ba3-8962-015908e02a63.png)
I have the latest version of python installed (3.10.5) and I just downloaded 1.38.0 but VapourSynth refuses to work.
[bugreport.txt](https://github.com/n00mkrad/flowframes/files/9086794/bugreport.txt)
Above are the logs, please help lol

**Comment by n00mkrad** [comment]
Known issue on multi-GPU systems, wait for next update
