### ISSUE TITLE
RIFE-NCNN-VS not working with frame deduplication

### ISSUE THREAD

**Issue by 4c30** [n00mkrad/flowframes#169]
Hello, as the title says i am having problems with the NCNN-VS implementation, when I use frame deduplication together with it.
*Edit: forgot to mention that i'm using the equivalent of 1.38.3, cloned from this repo*

When i'm using type 1 deduplication (slow) the NCNN-VS error is the following:
```[E] Traceback (most recent call last):
[E] File "src\cython\vapoursynth.pyx", line 2832, in vapoursynth._vpy_evaluate
[E] File "src\cython\vapoursynth.pyx", line 2833, in vapoursynth._vpy_evaluate
[E] File "E:\Program Files\Flowframes\FlowframesData\pkgs\rife-ncnn-vs\rife.vpy", line 11, in <module>
[E] clip = core.imwri.Read(r'E:\Program Files\Flowframes\video-temp\frames\%08d.png', firstnum=0)
[E] File "src\cython\vapoursynth.pyx", line 2580, in vapoursynth.Function.__call__
[E] vapoursynth.Error: Read: No files matching the given pattern exist
[E] pipe:: Invalid data found when processing input
```

While when i'm using type 2 deduplication (fast) the error is the following:
```[E] Python exception: Read: No files matching the given pattern exist
[E] Traceback (most recent call last):
[E] File "src\cython\vapoursynth.pyx", line 2832, in vapoursynth._vpy_evaluate
[E] File "src\cython\vapoursynth.pyx", line 2833, in vapoursynth._vpy_evaluate
[E] File "E:\Program Files\Flowframes\FlowframesData\pkgs\rife-ncnn-vs\rife.vpy", line 11, in <module>
[E] clip = core.imwri.Read(r'E:\Program Files\Flowframes\video-temp\frames\%08d.png', firstnum=0)
[E] File "src\cython\vapoursynth.pyx", line 2580, in vapoursynth.Function.__call__
[E] vapoursynth.Error: Read: No files matching the given pattern exist
```

After looking a bit into it, I think that when enabling deduplication, FlowFrames is writing frames to disk in the temp folder, instead of putting them in RAM. So when NCNN-VS tries to find frames in RAM, it can't.

**Comment by n00mkrad** [comment]
Cannot reproduce on latest codebase

**Comment by 4c30** [comment]
Weird, for me it gives an error for every video I have tried, for example you can try this one: https://pixabay.com/videos/bmx-halfpipe-bicycle-stunt-sports-6787/ at 1080p.
I have also tried deleting my FlowFrames and redownloading from this repo.

Steps to reproduce are just: 
- drop a video in the window, 
- select RIFE (NCNN/VS) as the AI and model v4.0
- in the settings, enable frame deduplication
- hit interpolate.

Then FlowFrames correctly extracts the frames (although to the disk) and deduplicates, but when it's time to interpolate it stops because of an error in vapoursynth.

Maybe I can send you the config.json file?
[config.zip](https://github.com/n00mkrad/flowframes/files/9311120/config.zip)

**Comment by n00mkrad** [comment]
Problem was caused by the "Import HQ JPEG instead of PNG" option.
VS was hardcoded to import PNGs.

Fixed: https://github.com/n00mkrad/flowframes/commit/13baf17f0f5ac0245777c6818da05fa4039a621d
