### ISSUE TITLE
Not enough disk space on C: to store temporary files!

### ISSUE THREAD

**Issue by noonesgonnasayyouraoki** [n00mkrad/flowframes#198]
make it so i can choose where to store said temporary files so this bullshit doesnt happen

**Comment by FelixKainz** [comment]
There is a setting to specify where to store your bullshit temporary files

**Comment by noonesgonnasayyouraoki** [comment]
> There is a setting to specify where to store your bullshit temporary files

for some reason that just happens to only apply to where the program itself is stored, not the temp files

**Comment by noonesgonnasayyouraoki** [comment]
well? any replies?

**Comment by FelixKainz** [comment]
What? You mean the path you can choose during install? That's not what I am talking about.
Open the app -> settings -> Application -> Temporary folder location.

**Comment by noonesgonnasayyouraoki** [comment]
thats the thing
i cant install it because i cant choose where it stores the temp files

**Comment by FelixKainz** [comment]
So you are talking about the installation process? A mention of hat could have helped

**Comment by noonesgonnasayyouraoki** [comment]
well? is this going to be fixed?

**Comment by n00mkrad** [comment]
> well? is this going to be fixed?

There is nothing to be fixed.

Clear up some space, HDDs and SSDs are cheaper than ever if you need more.

**Comment by noonesgonnasayyouraoki** [comment]
> > well? is this going to be fixed?
> 
> There is nothing to be fixed.
> 
> Clear up some space, HDDs and SSDs are cheaper than ever if you need more.

at least add an option to choose which drive to save the temp files at during the installation because there is no way im going to be able to clear 7 gb from my extremely convoluted C: drive
