### ISSUE TITLE
Output FPS and Speed values cannot be changed

### ISSUE THREAD

**Issue by DenisKen** [n00mkrad/flowframes#207]
![image](https://user-images.githubusercontent.com/15076521/218128225-b3f2fe68-acc0-4cf4-9908-189ccda83a03.png)

I can't change the number 0, this value never change

**Comment by FelixKainz** [comment]
Did you drag a video into the window?

**Comment by DenisKen** [comment]
> Did you drag a video into the window?

Solved. We need to `Browser (Folder)` or `Browser (Video)` in `input video (or frame folder)` field to load the images.
I was changing manually the input text, it seems to not work properly in that way...
