### ISSUE TITLE
How do I know the duration of the final video?

### ISSUE THREAD

**Issue by DenisKen** [n00mkrad/flowframes#208]
![image](https://user-images.githubusercontent.com/15076521/218288686-1a324bc4-9904-4690-8880-015b7e66bcfd.png)

The duration of the software says "Unknown". Is it possible to mannually calc the duration?

I'm using `Output FPS and Speed`: 12 x5 = 60 FPS.
And `181` frames..

**Comment by amauryjaphet** [comment]
181 frames at 12 fps is 00:00:15:01

**Comment by amauryjaphet** [comment]
he's not gonna close it???

**Comment by n00mkrad** [comment]
The duration refers to the input, not the output.

Showing the output duration is a good idea but not related to this issue.

**Comment by amauryjaphet** [comment]
yes
