### ISSUE TITLE
Flowframes generating video with wrong order pictures

### ISSUE THREAD

**Issue by DenisKen** [n00mkrad/flowframes#209]
![image](https://user-images.githubusercontent.com/15076521/218294102-d2bc5acc-36c3-423d-961b-4c18578a7082.png)

I have my pics ordered by numbers, but when I run `flowframes` the video result is a complete caos. It gets the pic number 84 and put first etc..

https://user-images.githubusercontent.com/15076521/218294088-fc209c0a-5fc1-42b8-8a08-7fd0f11b2e87.mp4

**Comment by n00mkrad** [comment]
Your images don't appear to be sorted alphabetically.

You need to have more zero-padding. E.g. 0001, 0002, etc.

Right now you it will be sorted as 1, 11, 12, 13, ...

**Comment by DenisKen** [comment]
> 

It worked, thank you!
