### ISSUE TITLE
When adding several PNG sequences, FPS is being set to 0 for each

### ISSUE THREAD

**Issue by Rembr** [n00mkrad/flowframes#210]
Hi and thank you for great program!
When adding several PNG sequences, FPS is being set to 0 for each, you have to first add each sequence to the main program window set FPS, and then transfer it to the queue, and then click " Add current configuration to queue" Is it possible to fix or am i doing something wrong? I work a lot with queue so please.

**Comment by n00mkrad** [comment]
Ah yeah it doesn't prompt for FPS when dropping it directly into the queue.
I can fix that

**Comment by Rembr** [comment]
Cool, that would be great, thank you!

**Comment by n00mkrad** [comment]
Fixed it.

You will now be asked to input the FPS when adding it to the queue, so later it will run without prompting you.
Will be in the next update.
