### ISSUE TITLE
UnicodeEncodeError 'charmap' codec can't decode characters in position 45-50 Characters maps to [unidentified]

### ISSUE THREAD

**Issue by idovidal** [n00mkrad/flowframes#212]
Hi

I get this message when i try to interpolate a video.

UnicodeEncodeError 'charmap' codec can't decode characters in position 45-50 Characters maps to [unidentified]

It worked before of different video.
What seem to be the problem?

**Comment by n00mkrad** [comment]
Use a path without special characters
