### ISSUE TITLE
May the Queue's Maxsize of Read_buffer in Rife-Cuda be a optional parameter?

### ISSUE THREAD

**Issue by GuileCyclone** [n00mkrad/flowframes#23]
I noticed that the speed of reading data is slower than predicting and writing. When I increased the maxsize of read_buffer to 160×args.wthreads in rife.py, there's a speedup in all processes, with the malloc memory increased too. So is it possible to make  queue's maxsize of read_buffer in rife.py be a parameter? It may be more efficient in machine with RAM more than 16GB.

**Comment by n00mkrad** [comment]
I will look into it and do some more benchmarking.

**Comment by n00mkrad** [comment]
I won't make it an option in the setting because personally I saw no speedup going from 200 to 600.

However, you will now be able to adjust the queue size in the config file (`rifeCudaBufferSize`).

https://github.com/n00mkrad/flowframes/commit/034794d5e5cae8de229e367438a3fbe0c3644f15
