### ISSUE TITLE
Audio out of sync with video if initial FPS is 23.976

### ISSUE THREAD

**Issue by Egor179** [n00mkrad/flowframes#235]
I convert movies and TV shows to 60 FPS.
As a rule, Russian serials and films run at 24, 25 FPS, and the sound does not get out of sync during interpolation.
With other films FPS 23.976, and here there are already problems, as a rule, the sound by the end of the film lags behind by 9.5-10 seconds.
I use RIFE 4.6 NCNN VapourSynth, h265 NVENC

**Comment by Egor179** [comment]
That there are no thoughts?

**Comment by n00mkrad** [comment]
Upload an example clip for me to test

**Comment by Egor179** [comment]
To be honest, I find it difficult to download a 2-hour movie, there are no problems with short videos (or the out of sync is not noticeable)

**Comment by Egor179** [comment]
So, for the test, I took an anime of 24 minutes, there is also a big sound out of sync. To control timing: 23:13
When setting the fps, the coefficient is 2.503 and the FPS is 60.01198, respectively, in the settings I select the maximum frame rate of 60.
https://drive.google.com/file/d/1NFF8ZiW59WHlcweKqpj6jTTKkHuAzNCD/view?usp=sharing, https://drive.google.com/file/d/1RERORUlztihA4V06zFqldkbm6umF0ZmI/view?usp=sharing

**Comment by n00mkrad** [comment]
Use factor 2.5x

That gets you a clean 60000/1001 FPS.
