### ISSUE TITLE
Non-integer interpolation factors?

### ISSUE THREAD

**Issue by pmarks-net** [n00mkrad/flowframes#25]
If I wanted to interpolate a video from (e.g.) 60 fps to 90 fps, I could do:

- x4 (240 fps)
- x4 (960 fps)
- Keep every 11th frame (87.27 fps)
- Speed up the audio by 3% and tweak the frame rate (90 fps)

Would it be possible for Flowframes to perform this x16/11 interpolation more efficiently, by taking advantage of the fact that most of the frames will be discarded?

**Comment by n00mkrad** [comment]
Use the "maximum output framerate" option in the video export settings.

RIFE itself can not do any factors other than 2^n, so the result will be downsampled.

**Comment by pmarks-net** [comment]
So if you input a 60 fps video, with x4 interpolation and 90 fps maximum output rate, what does "downsampled" mean?

60 x 4 = 240, which is 90 x 2.66.  Will Flowframes judder between "every 2nd frame" and "every 3rd frame", or does it somehow maintain equal frame pacing?

**Comment by Katzenwerfer** [comment]
The downsampling part is done by ffmpeg when encoding, after the interpolation steps.

Put it simply, it “dynamically” drops frames to meet the desired framerate

**Comment by pmarks-net** [comment]
So if you want to interpolate by a non-2^n factor (I guess non-integer is the wrong term) with minimal judder, you currently need to generate a _lot_ of extra frames, and then let ffmpeg decide which ones to keep.

Would it be possible to optimize this, by telling RIFE to interpolate at x16, but only actually do the work for 1-2 out of each 16 frames?

(If RIFE is not that flexible, then perhaps efficient non-2^n interpolation is a lost cause.)

**Comment by n00mkrad** [comment]
> So if you input a 60 fps video, with x4 interpolation and 90 fps maximum output rate, what does "downsampled" mean?
> 
> 60 x 4 = 240, which is 90 x 2.66. Will Flowframes judder between "every 2nd frame" and "every 3rd frame", or does it somehow maintain equal frame pacing?

Refer to the ffmpeg documentation: http://ffmpeg.org/ffmpeg-filters.html#fps

**Comment by n00mkrad** [comment]
> So if you want to interpolate by a non-2^n factor (I guess non-integer is the wrong term) with minimal judder, you currently need to generate a _lot_ of extra frames, and then let ffmpeg decide which ones to keep.
> 
> Would it be possible to optimize this, by telling RIFE to interpolate at x16, but only actually do the work for 1-2 out of each 16 frames?
> 
> (If RIFE is not that flexible, then perhaps efficient non-2^n interpolation is a lost cause.)

That is not possible as RIFE works recursively. It can't generate the frames for 16x without also generating 4x and 8x first.

**Comment by pmarks-net** [comment]
> Refer to the ffmpeg documentation: http://ffmpeg.org/ffmpeg-filters.html#fps

"Convert the video to specified constant frame rate by duplicating or dropping frames as necessary ... The default is near (round to nearest)"

Yes, that means ffmpeg creates judder, and you can reduce the judder by giving it more interpolated frames to pick from.  I'm just saying, if it were possible to avoid generating all those dropped frames in the first place, this process would be a lot more efficient.

**Comment by n00mkrad** [comment]
> > Refer to the ffmpeg documentation: http://ffmpeg.org/ffmpeg-filters.html#fps
> 
> "Convert the video to specified constant frame rate by duplicating or dropping frames as necessary ... The default is near (round to nearest)"
> 
> Yes, that means ffmpeg creates judder, and you can reduce the judder by giving it more interpolated frames to pick from. I'm just saying, if it were possible to avoid generating all those dropped frames in the first place, this process would be a lot more efficient.

I know, but it's not possible.

Wait for FLAVR which can do any factor.

**Comment by pmarks-net** [comment]
Thanks for checking.  I'll see how FLAVR's doing someday.
