### ISSUE TITLE
GPU is not being utilized by frame extraction

### ISSUE THREAD

**Issue by SkyEngine-OSP** [n00mkrad/flowframes#29]
I have a freshly installed Windows 10 Pro on a Xeon E3-1220 V3 with ASUS TUF GTX 1650 4GB OC GDDR6 and 8GB of total RAM Capacity. The onboard graphics processor has already been disable via BIOS and is no longer appearing neither in Device Manager nor in dxdiag command.

I'm trying to interpolate one of my old videos from 29.97 to ~60fps but i can't help but notice that Flowframes only uses the CPU for extracting the frames. CPU runs at an average of 80% utilization with no other running apps while the GPU remains at 2-6%

I have already tried playing ith the Pytoch and NCNN GPU IDs from 0 to 1 and nothing changed. is this normal?

**Comment by richardletshacks** [comment]
Yes. CPU is used for extracting frames.

**Comment by n00mkrad** [comment]
Frame extraction can't be accelerated by GPU.

**Comment by SkyEngine-OSP** [comment]
thanks guys! had no idea so i had to ask. cheers.

**Comment by SkyEngine-OSP** [comment]
![image](https://user-images.githubusercontent.com/12471935/109414262-ff748080-79ec-11eb-8dee-89f625fbf710.png)

i assume interpolation process should utilize GPU? in my case, apparently, it still does not.

**Comment by SkyEngine-OSP** [comment]
can confirm i have the latest Nvidia GPU Drivers installed (461.72) and the system recognizes 1650 as its only and primary GPU
![image](https://user-images.githubusercontent.com/12471935/109414371-79a50500-79ed-11eb-95e7-9bbf7ab6bc4e.png)

**Comment by n00mkrad** [comment]
Check the GPU ID option in the settings, it should be set to 0 if you have one GPU.

**Comment by flecca** [comment]
If I have an iGPU and a dedicated GPU, what value should the GPU ID be set to for selection of the dedicated GPU?

**Comment by AngeryLettuce** [comment]
> If I have an iGPU and a dedicated GPU, what value should the GPU ID be set to for selection of the dedicated GPU?

did u figure it out?
