### ISSUE TITLE
JPG Output Not Working

### ISSUE THREAD

**Issue by FlowDownTheRiver** [n00mkrad/flowframes#3]
I checked the jpg output option to save space but it is still exporting png.
Can you fix that?

**Comment by n00mkrad** [comment]
Fixed in v16.

**Comment by FlowDownTheRiver** [comment]
Thank you very much 💯

**Comment by FlowDownTheRiver** [comment]
I just updated to v16 from in app update option,still it is exporting png instead of jpg. Can you confirm that?
