### ISSUE TITLE
GIF Files doesnt keep alpha channel

### ISSUE THREAD

**Issue by nonunknown** [n00mkrad/flowframes#34]
I tried with a gif, and the alpha channel information is lost

RIFE:
![a1-4x-RIFE](https://user-images.githubusercontent.com/58845030/110940576-e38aac00-8315-11eb-8ac4-5d8275a05c35.gif)

NORMAL:
![a1](https://user-images.githubusercontent.com/58845030/110940580-e4234280-8315-11eb-9b73-bf5ca0cc11e5.gif)

**Comment by n00mkrad** [comment]
Alpha isn't supported natively with RIFE, but you can enable it in the interpolation settings in Flowframes (it will interpolate the alpha channel separately and then merge it)
