### ISSUE TITLE
Web Installer doesn't work anymore

### ISSUE THREAD

**Issue by Boeblahoebla** [n00mkrad/flowframes#341]
Hi

The web installer doesn't work anymore. Both the German & the USA servers to download have problems with the SSL/TSL handshake.

![image](https://github.com/user-attachments/assets/1ec7b952-7985-43fb-9bea-9ce1bd9fedf2)

**Comment by n00mkrad** [comment]
Which server? EU?

**Comment by n00mkrad** [comment]
Messed up SSL certificate again, fixed. Will also verify USA server but that should still run as before
