### ISSUE TITLE
Can't download any model

### ISSUE THREAD

**Issue by lea-boulay** [n00mkrad/flowframes#342]
Hello, I've just installed Flowframes, I've imported my video but after extracting the frames it displays this and I've tried with all the other models it does exactly the same thing, I'm well connected to the internet and I had a lot of space available on my ssd.
<img width="746" alt="screenshot123" src="https://github.com/user-attachments/assets/bb952a75-a5f8-42c8-bacb-504115558772" />

**Comment by n00mkrad** [comment]
Messed up SSL certificate again, fixed.
