### ISSUE TITLE
Improve Sprite interpolation

### ISSUE THREAD

**Issue by nonunknown** [n00mkrad/flowframes#35]
I would like to show some results with some sprite animations, maybe training the model with sprites could solve the problem?

ps: all gifs are <= 40 FPS

Original 5 FPS:
![flame](https://user-images.githubusercontent.com/58845030/111069226-dd7a0400-84aa-11eb-8921-fe7caa878d69.gif)

2x 10 FPS:
![flame-2x-RIFE](https://user-images.githubusercontent.com/58845030/111069246-f4205b00-84aa-11eb-9c1b-01fde5251d0b.gif)

4x 20 FPS:
![flame-4x-RIFE](https://user-images.githubusercontent.com/58845030/111069253-f8e50f00-84aa-11eb-9600-c142b3848d99.gif)

8x 40FPS:
![flame-8x-RIFE](https://user-images.githubusercontent.com/58845030/111069259-fb476900-84aa-11eb-826a-f36d6b925b44.gif)

**Comment by n00mkrad** [comment]
There's nothing I can really do here.

Which model did you use?

**Comment by nonunknown** [comment]
![image](https://user-images.githubusercontent.com/58845030/111069374-917b8f00-84ab-11eb-8589-a7c59b2d36bb.png)

**Comment by n00mkrad** [comment]
That's not the model.

![image](https://user-images.githubusercontent.com/61149547/111069463-74f04e80-84cd-11eb-8cf0-53fb03da327b.png)

**Comment by nonunknown** [comment]
hahah LOL

I'm using 2.0

**Comment by n00mkrad** [comment]
Update to the latest version and try 1.8 or 2.2.

Apart from that there's nothing I can do to improve it.
