### ISSUE TITLE
Video FPS: Not Found on (1.22.3-Full.7z)

### ISSUE THREAD

**Issue by luca2125** [n00mkrad/flowframes#38]
Hi,

I have tried to interpolate this video and I get this message:

[LogoFinal.zip](https://github.com/n00mkrad/flowframes/files/6175921/LogoFinal.zip)

Loading metadata...
Video FPS: Not Found - Total Number Of Frames: 1
Canceled interpolation.

This was not happen in the previous version.

I have tried the version 1.20.4 and work but produce flickering.

Here the test video
[Battle1.zip](https://github.com/n00mkrad/flowframes/files/6176098/Battle1.zip)

I have set checked "don't interpolate scene changed" to 0.1 without get better result.

Can you help me please ?

Thanks !

**Comment by n00mkrad** [comment]
Reproduce it and send the logs located in FlowframesData/logs/.

**Comment by luca2125** [comment]
https://user-images.githubusercontent.com/55355625/111905150-93fd5c00-8a4a-11eb-98b5-c24eea5f43ae.mp4

[logs_1.20.4.zip](https://github.com/n00mkrad/flowframes/files/6177407/logs_1.20.4.zip)
[logs_1.22.3.zip](https://github.com/n00mkrad/flowframes/files/6177408/logs_1.22.3.zip)

Attached the log and the final result of version 1.20.4

**Comment by luca2125** [comment]
https://user-images.githubusercontent.com/55355625/111905271-16861b80-8a4b-11eb-836d-e693a0fd31d5.mp4

**Comment by bui-vui** [comment]
I have this problem too but only after I installed the Python dependencies for Pylock Implementation. Does anyone know how to remove the Python dependencies?

**Comment by n00mkrad** [comment]
Closing as this is an old version anyway - Will reopen if problem persists.

**Comment by luca2125** [comment]
The problem persist wth the last updated version.

I have uploaded on google drive the original file and the output file so you can see the result:

https://drive.google.com/drive/folders/1wmqI4Yw-8y2DFDa-iylUA7_mdRjKdrv2?usp=sharing

There is stuttering after the first 5 seconds.

**Comment by n00mkrad** [comment]
This is simply a limitation of the AI. Nothing you can do.

**Comment by luca2125** [comment]
The new models in the near future can be work better and solve this problem ? Or it is improbable ?
