### ISSUE TITLE
Add option to use NVENC Encoder for FFMPEG

### ISSUE THREAD

**Issue by ensingerphilipp** [n00mkrad/flowframes#39]
Feature Request to add the option of using Hardware accelerated encoding with ffmpeg.
Feature Request to add the option of using more threads / cores with ffmpeg.

I just ran a Frame Interpolation on a 45 Minute 4K Video and after successful interpolation the encoding of the resulting video using ffmpeg is only running on cpu (AND only on 2 Core out of 8 available) which slows down the process a lot. 

The encoding takes longer than the actrual frame interpolation took.

System: 
Ryzen 7 4800H 8 Core 16 Threads
Nvidia RTX 2060

**Comment by n00mkrad** [comment]
NVENC is already an option.

**Comment by ensingerphilipp** [comment]
sorry my bad was about to correct myself
