### ISSUE TITLE
Replace the torch folder to support Ampere architecture graphics cards

### ISSUE THREAD

**Issue by YiWeiHuang-stack** [n00mkrad/flowframes#4]

**Comment by YiWeiHuang-stack** [comment]
![flowframes](https://user-images.githubusercontent.com/68835291/100752670-d3fcec80-3423-11eb-8b1e-d9928dcff782.jpg)
![dain0 48](https://user-images.githubusercontent.com/68835291/100752684-d65f4680-3423-11eb-9fda-07f875448b8c.jpg)

**Comment by YiWeiHuang-stack** [comment]
![3090](https://user-images.githubusercontent.com/68835291/100752883-13c3d400-3424-11eb-9301-01d8eabbe215.png)

**Comment by n00mkrad** [comment]
I do not have an Ampere GPU and can't test this.

Support will be added soon.
Until then, you can try using system python (see readme).
