### ISSUE TITLE
torch dependency not installing

### ISSUE THREAD

**Issue by Stebulous** [n00mkrad/flowframes#42]
Heres the error log after trying multiple times using the page that shows by default and adding --user to the end. Nothing seems to work. Im not sure if I messed up my python installation or what but other python programs work fine. 

![8SOXE5p 1](https://user-images.githubusercontent.com/26839273/112365712-5862cc00-8cae-11eb-9212-9e9be511bc6b.png)

**Comment by n00mkrad** [comment]
...what are you trying to o here?

**Comment by Stebulous** [comment]
> ...what are you trying to do here?

when I try to use flowframes it tells me I'm missing torch dependency so I use [the page provided](https://github.com/n00mkrad/flowframes/blob/main/PythonDependencies.md) and it errors like this. 

this is the latest error I'm getting trying to interpolate
![vaheLnr 1](https://user-images.githubusercontent.com/26839273/112367232-0d49b880-8cb0-11eb-958c-7732921fe1b3.png)

**Comment by Stebulous** [comment]
ok heck forget the torch problem i was also on CUDA instead of Vulkan that's uhhh one problem

seems to work now.
