### ISSUE TITLE
Audio is out of sync

### ISSUE THREAD

**Issue by luca2125** [n00mkrad/flowframes#43]
Hi,

I have used the last version of flowframes but the audio is out of sync:

https://drive.google.com/file/d/1Sc85Zcbn2Li3Dt0YkBvyrnxu-JBE3-Mw/view?usp=sharing

I have tried to change many options but the result is the some.

Hope is possible find a solution.

**Comment by n00mkrad** [comment]
Investigating.

Try disabling auto-encode for now.

**Comment by n00mkrad** [comment]
The problem is that this video is variable framerate (VFR).

I have to see if I can fix this...

**Comment by luca2125** [comment]
thank you !!

Wating for your update.

**Comment by n00mkrad** [comment]
Is that good?

https://cdn.discordapp.com/attachments/507908887123591177/827521479914029066/intro_640-2x-RIFE-RIFE23-60fps.mp4

**Comment by luca2125** [comment]
Perfect !! Can you please share the last update with this modification ?

**Comment by n00mkrad** [comment]
Fixed in this commit: https://github.com/n00mkrad/flowframes/commit/b3ab84646b72b3e716edd513bf2726d0196d717b
