### ISSUE TITLE
bug reports

### ISSUE THREAD

**Issue by luca2125** [n00mkrad/flowframes#44]
Hi,

Thank you for your last fix I have tested it and work fine.

Now I report you other bugs:

1) Batch processing: If choose folder (and not single file)  if I press "interpolate" there is a crash (this was not happen in the previous version).
2) I have gtx 1060 If i choose "cuda/pytorch" the process use the CPU and not GPU. If I set "Vulcan" work fine (again, this was not happen in the previous version).
3) Strage frame at 20 seconds in this video:

[look_at_20_second.zip](https://github.com/n00mkrad/flowframes/files/6249726/look_at_20_second.zip)

Hope is possible solve.

Thank you !

Marco

**Comment by n00mkrad** [comment]
What version are you on?

**Comment by n00mkrad** [comment]
Also, batch processing doesn't work on a folder. You have to select all the videos.

**Comment by n00mkrad** [comment]
> Strage frame at 20 seconds in this video:

This seems to be a problem with blended scene frames in combination with VFR videos. Using "Basic" scene change mode works.

**Comment by luca2125** [comment]
These are the setting that I have used:

![setting](https://user-images.githubusercontent.com/55355625/113422046-61e5e580-93cc-11eb-922a-5bfeee6a6435.png)

About the version I have re-compiled the last soruce code on this repository.

Seem already set basic scene changed

**Comment by luca2125** [comment]
I confirm the last update introduce this bug (in this zip file there is the previous and current result) :

[regression.zip](https://github.com/n00mkrad/flowframes/files/6250044/regression.zip)

I have re-interpolate again my videos with the some setting.

With the previous version is not present this strange frame.

So at the moment I will keep only the first video where seem not present this artifact.

Thank you again !

**Comment by n00mkrad** [comment]
> I confirm the last update introduce this bug (in this zip file there is the previous and current result) :
> 
> [regression.zip](https://github.com/n00mkrad/flowframes/files/6250044/regression.zip)
> 
> I have re-interpolate again my videos with the some setting.
> 
> With the previous version is not present this strange frame.
> 
> So at the moment I will keep only the first video where seem not present this artifact.
> 
> Thank you again !

That's because the previous version doesn't support VFR properly.

**Comment by luca2125** [comment]
Do you think there is a way to solve it in the future ?

This artefact is present in many videos that generate the new updated version.

**Comment by n00mkrad** [comment]
> Do you think there is a way to solve it in the future ?
> 
> This artefact is present in many videos that generate the new updated version.

You mean the bugged frame when using scene blending?

**Comment by luca2125** [comment]
I have scene "fix change mode" to "basic", like the screenshot.

And with this setting there is this aftefact.

I need to change this setting ?

**Comment by n00mkrad** [comment]
> I have "scene fix change mode" to "basic", like the screenshot.
> 
> And with this setting there is this aftefact.
> 
> I need to change this setting ?

Yes.

"Fancy" still works in normal (constant frame rate) videos. VFR will be fixed later on.

**Comment by n00mkrad** [comment]
VFR now works the way it should.

**Comment by arbdfsf** [comment]
It stays like this and it doesn't do anything anymore, how do I solve it?

**Comment by arbdfsf** [comment]
It stays like this and it doesn't do anything anymore, how do I solve it?


![Captura de pantalla (39)](https://user-images.githubusercontent.com/111559084/185559466-767e0a72-62db-43fb-a181-bfe401200b48.png)
