### ISSUE TITLE
Last version produce error message

### ISSUE THREAD

**Issue by luca2125** [n00mkrad/flowframes#46]
Hi,

Just installed last version by compiled the last update source code im this repository. There are 2 problems:

Error message:
![bug1](https://user-images.githubusercontent.com/55355625/113673826-bb466100-96b9-11eb-8bd7-dff1438a1fc3.png)

Warning: don't have sufficient privilege to enable development mode for nvidia CUDA mode.

**Comment by n00mkrad** [comment]
Can you contact me on Discord about the problem? Would be quicker.
nmkd#1425
