### ISSUE TITLE
4 bugs with 1.23.4 ordered by "most" important (1) to "least" important. (4)

### ISSUE THREAD

**Issue by glasshopperwastaken** [n00mkrad/flowframes#47]
So, I've encountered some bugs in 1.23.4
1. VP9 doesn't copy over audio to interpolated video
2. Making the hidden command window visible makes the progress bar not update until interpolation is finished (Might be intentional)
3. Every time you want to use DAIN it needs to re-install, but DAIN isn't really relevant anymore so shrug
4. And lastly, mode 2 of de-duplication will say it deleted all the other frames from the full video, instead of just the trimmed part. It won't actually process the parts that aren't in the trimmed area, but it will say it deleted frames from the deleted area from the trim. (this is confusing holy heck)

**Comment by n00mkrad** [comment]
1) Send me a video to reproduce

2) Known, is by design

3) What do you mean by re-install? Flowframes is portable.

4) Just fixed: https://github.com/n00mkrad/flowframes/commit/ad28c6a121f293bf61a46bf9e5b2e0212217c611
