### ISSUE TITLE
No Cuda?

### ISSUE THREAD

**Issue by smepper2** [n00mkrad/flowframes#48]
Hi,
I have this issue in two Laptops, both win10, i7 processors, one with 1050gtx and one 2070Max-q

Flowframes (FullVersion) says in the Welcome Text that it found the Graphics Card and shows the right model name.

But when I start interpolarion the text in the black window says no cuda - running in CPU. It works and results are amazing (I donated) but it takes forever. Any solutions?

**Comment by n00mkrad** [comment]
Can you send a screenshot of your the "Settings -> AI Specific Settings" page?

**Comment by smepper2** [comment]
Here are the AI settings

**Comment by smepper2** [comment]
![Screenshot_20210413-143306](https://user-images.githubusercontent.com/82447172/114552776-3cc36380-9c65-11eb-8960-9b75cf61932b.png)

**Comment by Tsubajashi** [comment]
Hi!
Did you already test with pytorch gpu Id 0?
Atleast that's what's the standard on my laptop, that may work for you.

Just to make sure it isn't picking up the wrong gpu for inference.

Might or might not work. YMMV.

**Comment by n00mkrad** [comment]
Try GPU ID 0.

**Comment by smepper2** [comment]
OK that worked! I think I changed that setting because it wasnt working for me at all in the beginning with Default settings. Thanks a lot for replying!
