### ISSUE TITLE
Confused about the program

### ISSUE THREAD

**Issue by SpinnerChris** [n00mkrad/flowframes#49]
It says the RTX 3000 one which is the biggest in size is also compatible with older cards, would the RTX 2060 be compatible as-well?

**Comment by barbaduk** [comment]
> 
> 
> It says the RTX 3000 one which is the biggest in size is also compatible with older cards, would the RTX 2060 be compatible as-well?

If you don't have RTX 3000 series card, then you don't need support for it. Just download Full version

**Comment by n00mkrad** [comment]
> It says the RTX 3000 one which is the biggest in size is also compatible with older cards, would the RTX 2060 be compatible as-well?

Yes, it's compatible as well.

However, it's a waste of space if you have a 20xx card, that's why I also offer the "Full" version with an older version of Pytorch that is smaller but doesn't support Ampere.

**Comment by SpinnerChris** [comment]
Is the download normally this slow? It's been almost an hour and the download is only 98.3 MB out of 712 MB. I know it's not my internet.

**Comment by n00mkrad** [comment]
> Is the download normally this slow? It's been almost an hour and the download is only 98.3 MB out of 712 MB. I know it's not my internet. I've downloaded some 500 MB projects from github today and it only takes about 10-20 seconds.

Looks like my hoster is having some problems today. Try again, it should be faster now.

**Comment by SpinnerChris** [comment]
Yeah, I noticed the speedup.  I looked back at my downloads and it had already finished. Thanks for the help!
