### ISSUE TITLE
Cannot install FF 1.24.1

### ISSUE THREAD

**Issue by ITAC85v2** [n00mkrad/flowframes#50]
I'm having issues installing FlowFrames 1.24.1.
When I'm using the installer, it gives me an error about not having enough disk space on C:
![image](https://user-images.githubusercontent.com/47468644/116324956-176b4500-a78f-11eb-8930-29d78749556d.png)
Here's the amount of space I have free (as of writing this):
![image](https://user-images.githubusercontent.com/47468644/116325004-2b16ab80-a78f-11eb-8751-b9754cd18366.png)

In later versions of FlowFrames, there should be a feature in the installer to specify the temporary file location during the installation to prevent this from happening (as I have other drives that have enough space for temporary files).

**Comment by n00mkrad** [comment]
I can't account for people with this little storage on their boot drive.
