### ISSUE TITLE
Flowframes doesn't preserve color information

### ISSUE THREAD

**Issue by ripandtearr** [n00mkrad/flowframes#52]
On 1.24.6 - 
I cannot get Flowframes to retain the correct colors. Input files are yuv420p bt709/bt709/bt709. Output files are (where applicable for the output codec) yuv420p bt709/bt709/bt709. Yet, the colors are seriously yellowed. I don't know what the problem is.

I tried huffyuv with yuv420p specified, lossless 264, non-lossless 264. All yellowed.

**Comment by n00mkrad** [comment]
Try adding the following in Settings -> Developer Optoins ("Debugging/Experimental" in previous versions) -> FFmpg Custom Output Arguments:

`-colorspace:v "bt709" -color_primaries:v "bt709" -color_trc:v "bt709" -color_range:v "tv"`

I will investigate the option to automatically select this if the input is also bt709, but for now how you have to do it this way.

**Comment by ripandtearr** [comment]
The above flags didn't work, but n further search, this combination of flags in ffmpeg unfucks the colors:

` -pix_fmt yuv420p -vf scale=out_color_matrix=bt709 -colorspace bt709 -color_primaries bt709 -color_trc bt709`

If you omit "-vf scale=out_color_matrix=bt709" it won't work. Apparently, -colorspace and -color_primaries and -color_trc flags only set the metadata.
 
I haven't verified it's 100% correct colors, but it looks so. Certainly better than before. ffmpeg makes me want to chop my head off.

**Comment by n00mkrad** [comment]
Right, I think that was it. I'm currently checking if I can automate this in Flowframes.

**Comment by n00mkrad** [comment]
Added automatic color transfer: https://github.com/n00mkrad/flowframes/commit/55c0f5904cd49e84bf2c5274e560776eba1c896f

**Comment by mirh** [comment]
https://github.com/k4yt3x/video2x/issues/403
The proper "universal" fix (or at least workaround for the time being) is to tag the output files with the bt.601 colorspace, not to stubbornly force bt.709.

**Comment by ValZapod** [comment]
> The proper "universal" fix (or at least workaround for the time being) is to tag the output files with the bt.601 colorspace, not to stubbornly force bt.709.

No, the fix is to force 709. It is dumb to use 601 in 2022. For example, Nvidia Geforce Exp. records 4K stuff in avc in bt.601 (and it is real 601) but VLC does not support 4k with 601 and goes to 709. Hilarious. Use mpv.

**Comment by mirh** [comment]
I'm really neutral as far as colorspaces go, but this also means I don't care about what they are as long as the links in the chain understand each other and the final image is right. 

Of course you can even force 709, all roads lead to Rome with enough detours. 
But then you'd also have to take care of matrix conversion (because as we know, that's not what ffmpeg targets when extracting pngs). In this sense just adding the bt.601 flag is simpler. 

> but VLC does not support 4k with 601 and goes to 709. 

That sounds a bug on their side to be really honest. I get guessing defaults when it's not specified, but metadata is metadata.

**Comment by ValZapod** [comment]
> That sounds a bug on their side to be really honest

Of course. Only I opened two bugs in vlc.

>this also means I don't care about what they are as long

Ideally for best codepoints utilisation primaires and white point should be the only thing that defines the matrix. So for BT.470 System M BT.601 matrix, for BT.709 pramaries BT.709 matrix, 2020 same.
