### ISSUE TITLE
FFmpeg error 

### ISSUE THREAD

**Issue by Rafey733** [n00mkrad/flowframes#53]
what is this error i keep getting it?

**Comment by n00mkrad** [comment]
No idea if you don't describe it lmao

**Comment by Rafey733** [comment]
So i want my video from 30 fps to 60 fps and i start to interpolate and it stops at 46% and it says
![error](https://user-images.githubusercontent.com/83764720/117545925-28864280-b028-11eb-9275-d2f66f24ea85.jpg)

**Comment by n00mkrad** [comment]
Read #known-bugs on the Discord
