### ISSUE TITLE
Avoid copying files when possible

### ISSUE THREAD

**Issue by Athari** [n00mkrad/flowframes#58]
Copying "compatible" files instead of reencoding is a good improvement, but it'd be even better to symlink/hardlink source files to avoid wasting disk space. I found the `allowSymlinkEncoding` key in the config (which doesn't seem to be in the GUI), but this option isn't used in the compatible files code path for some reason (admittedly, I haven't really explored the code). There's a lot of duplication happening on various stages, especially if image sequences are used as input and output (all of input, half of interpolated, iiuc), so it'd be great if FlowFrames used links whenever possible.

**Comment by n00mkrad** [comment]
Pretty sure this is not possible as the interpolation code won't accept symlinks.

**Comment by Athari** [comment]
Weird, symlinks are mostly undetectable for apps, unless they check for specific flags for some reason. Hm. If forking and fixing isn't an option, then hardlinks maybe? In theory, they're harder to detect.

**Comment by n00mkrad** [comment]
I investigated this again and it seems to be possible. I'll look into implementing this.

**Comment by n00mkrad** [comment]
Seems to work. Will be in 1.27.1

https://github.com/n00mkrad/flowframes/commit/fd9f5235b156f16f1bfcee684fcfabe1f18c181a
