### ISSUE TITLE
Are there any plan to integrate deep animation interpolation in the wild? 

### ISSUE THREAD

**Issue by YiWeiHuang-stack** [n00mkrad/flowframes#60]

**Comment by n00mkrad** [comment]
Yes, but only if the inference code gets a bit cleaner, right now there's only validation code that would be hard to integrate.

**Comment by YiWeiHuang-stack** [comment]
I have the code that can run own frames, but cannot use the SGM flow , and I measured that without cupy is five times slower than with cupy.
Hope the code is helpful to you

[AnimeInterp.zip](https://github.com/n00mkrad/flowframes/files/6539163/AnimeInterp.zip)

**Comment by n00mkrad** [comment]
> I have the code that can run own frames, but cannot use the SGM flow , and I measured that without cupy is five times slower than with cupy.
> Hope the code is helpful to you
> 
> [AnimeInterp.zip](https://github.com/n00mkrad/flowframes/files/6539163/AnimeInterp.zip)

Thanks for the code!

I tried it, but it always adds padding to the interpolated frames, making the resulting video look bad:


https://user-images.githubusercontent.com/61149547/119501241-f9323e00-bd68-11eb-84ef-1bb09c0ac071.mp4

**Comment by YiWeiHuang-stack** [comment]
I'm sorry, but I don't have enough time to fix this problem, it seems that the bug is easy to be solved by fixing the padding. maybe you need to try to fix it yourself
