### ISSUE TITLE
What happened to CAIN? Why is he no longer in the program?

### ISSUE THREAD

**Issue by bryanndg** [n00mkrad/flowframes#61]

**Comment by n00mkrad** [comment]
Unstable, produces glitches on most GPUs.

**Comment by n00mkrad** [comment]
https://github.com/nihui/cain-ncnn-vulkan/issues/12

**Comment by bryanndg** [comment]
thank you so much

**Comment by Lucaiii** [comment]
He is hiding from the wrath of God after killing his brother Abel. Sorry.
