### ISSUE TITLE
put as rar pls

### ISSUE THREAD

**Issue by joshuaword2alt** [n00mkrad/flowframes#62]
it has my to not run i posted on itch it says 

<p style="line-height: 1.4; margin-top: 5px; color: rgb(207, 207, 207); font-family: Lato, Lato, LatoExtended, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(35, 35, 35); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">but it saids on my pc&nbsp;</p><p style="line-height: 1.4; color: rgb(207, 207, 207); font-family: Lato, Lato, LatoExtended, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(35, 35, 35); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Windows protected your PC<br>Microsoft Defender SmartScreen prevented an unrecognised app from starting. Running this app might put your PC at risk.<br>Application: Publisher:&nbsp;<br></p>
FlowframesInstaller1.24.6 (2).exe
--
Unknown publisher

**Comment by n00mkrad** [comment]
Click on More and Run Anyway
