### ISSUE TITLE
MKV track name 

### ISSUE THREAD

**Issue by ketworie** [n00mkrad/flowframes#63]
When interpolating MKV with audio track named "LPCM->FLAC" the audio is missing.
If you choose to extract audio separately, program just stops on "extracting audio" stage.
Renaming track to "FLAC" helped.
Version 1.26.1

**Comment by n00mkrad** [comment]
Can you send the problematic video file?

**Comment by ketworie** [comment]
Output: MKV
Model: RIFE 2.3
Sample: https://mega.nz/file/ACJShZAL#VSjw5oXiVU2ewPlFYe9g94IquOKftUes7EgNdEjMiQc

**Comment by n00mkrad** [comment]
Works fine in 1.27.2 (current codebase).
