### ISSUE TITLE
Bug fix or feature request - jpeg interpolated frames

### ISSUE THREAD

**Issue by NoUserNameForYou** [n00mkrad/flowframes#64]
Using 1.72 here, in the debug menu options there's a section called jpeg interpolate, when set to true, it does't output interpolated frames as jpeg, it still does png.

I'm going through my old HSBS movies and it png frames take a toll on the HDD space too much.

Can you help?

**Comment by n00mkrad** [comment]
This is currently not supported. It also degrades quality more.

Use auto-encode with a fast CPU/codec to avoid having too many PNGs.

**Comment by NoUserNameForYou** [comment]
> It also degrades quality more.

Even at 100%? 

Thanks anyway. Issue closed then.

**Comment by NoUserNameForYou** [comment]
> This is currently not supported. It also degrades quality more.
> 
> Use auto-encode with a fast CPU/codec to avoid having too many PNGs.

Mate I didn't want to create another issue so I'm going to ask here again.

Official rife repo states they have 16x model, can it be added ?

**Comment by n00mkrad** [comment]
There is no 16x model, RIFE can only do 2x. All higher factors just do 2x multiple times.

16x would be 2x2x2x2x which would noticably degreade quality, so personally I think it's not worth it.

**Comment by NoUserNameForYou** [comment]
Thanks for the answer. Your app downloads 4x and 8x models separately and the rife repo stated they created a video out of only two frames with 16x so I got confused

Thanks!

**Comment by n00mkrad** [comment]
My app does not download 4x and 8x models separately for RIFE.

Maybe you're thinking of FLAVR.

**Comment by NoUserNameForYou** [comment]
Sorry for wasting your time, you are right, it was flavr.
