### ISSUE TITLE
error while interpolating

### ISSUE THREAD

**Issue by cinqui** [n00mkrad/flowframes#66]
error:

A python error occurred during interpolation!
Check rife-cuda-log for details.
[WinError 193] %1 is not a valid win32 app.
Error loading (directory)

**Comment by Tsubajashi** [comment]
we need the logs to understand what exactly is going wrong.

**Comment by cinqui** [comment]
hi! where can I find the logs?

**Comment by cinqui** [comment]
i reinstalled it, and now it is working. thanks!

**Comment by cinqui** [comment]
(the problems were the libs)
