### ISSUE TITLE
What is this?

### ISSUE THREAD

**Issue by jepson24** [n00mkrad/flowframes#68]
Unhandled UI Exception!

Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.

Stack Trace:
   at HTAlt.WinForms.HTButton..ctor()
   at Flowframes.Form1.InitializeComponent()
   at Flowframes.Program.Main()

The error has been copied to the clipboard. Please inform the developer about this.

**Comment by itzaeon** [comment]
I also get this error on Windows 10 1607.

**Comment by Tsubajashi** [comment]
are you both on 1607?

**Comment by Tsubajashi** [comment]
so i will just assume you both run on Windows 10 1607 - It isnt supported by Microsoft anymore, and its about time to change away from that unsupported Windows 10 release.
See here for details: https://docs.microsoft.com/en-us/lifecycle/products/windows-10-home-and-pro

**Comment by okh-mzny** [comment]
I'm running 2016 LTSB which is based on 1607 and still under support, I get no such error.

You are probably missing some .NET runtime, or you don't have the right version.
I would suggest getting the latest version 4.8 from https://dotnet.microsoft.com/download/dotnet-framework/thank-you/net48-web-installer
