### ISSUE TITLE
Interpolation has been paused because you are running out of disk space

### ISSUE THREAD

**Issue by okh-mzny** [n00mkrad/flowframes#69]
Would it be possible to include an option to disable this warning? 

It worked before without any interruptions, but now I get the warning.

For context, I'm running the entire interpolation inside of a RAM-Disk which resides entirely in RAM and therefore can't be too large. I only have a 4GB RAM-Disk thats enough for my purposes but prompts this warning.

Hope you can include a config option to skip disk space checks.
Cheers!

**Comment by n00mkrad** [comment]
You currently can't do this in the GUI.

As a workaround, open the Debug Tools window (leftmost of the 4 buttons in the main window), click the second tab (Config Editor), then find `lowDiskSpaceCancelGb` and `lowDiskSpacePauseGb` and set both to 0.

**Comment by okh-mzny** [comment]
Sorry for the late reply, Github did not notify me despite being subscribed to this issue.

But the config worked flawlessly, thank you very much!
