### ISSUE TITLE
Hardcoded PNG image format in code. 

### ISSUE THREAD

**Issue by h0x91b** [n00mkrad/flowframes#7]
Hi,

Got an exception and after short debugging found that the image format is hardcoded...

Image sequence can be encoded in jpeg as in my case or some else image format, code should check correct type.

https://github.com/n00mkrad/flowframes/blob/8f77f0509893f6b0c618bfb9145fbe38dc0f9cb6/Pkgs/rife-cuda/interp-parallel.py#L51

**Comment by n00mkrad** [comment]
The input format is hardcoded to guarantee compatibility.

Flowframes V17 (and the latest source) have an import process that allows you to load any image format that's compatible with FFmpeg (PNG/JPG/BMP, possibly more).
