### ISSUE TITLE
Flowframes not respecting output folder

### ISSUE THREAD

**Issue by Super4Jet** [n00mkrad/flowframes#72]
After selecting the video input and defining the output directory, I would expect _all_ output to go to said output directory. But instead, it creates a directory right next to the input file and dumps all the frames there. What might not seem like a big issue gains relevance when using a NAS and/or Hard Drives to store videos (especially SMR technology, which is not meant for writing small files), and suddenly you end up with extreme latencies or a clogged pipe when reading other files from there. The input directory should be seen as input-only (=read only) and output directory should be used for any action that requires writes (=read-write).
I'm using the most recent commit (https://github.com/n00mkrad/flowframes/commit/bebd947b7acea6249368045c874c123529bd4d32).

**Comment by xpscyho** [comment]
in the settings there is an option to change the temp folder. is that what you are referring to?

**Comment by Super4Jet** [comment]
Might be, it's still running and I can't open the settings at this time. If there is an option to instead always use the output directory, then yes, that would solve my issue (other than not being turned on by default).

**Comment by Super4Jet** [comment]
Ah, it is, just not by default. Thanks
