### ISSUE TITLE
"Not enough disk space on C: to store temporary files!"

### ISSUE THREAD

**Issue by CodeDiseaseDev** [n00mkrad/flowframes#74]
![image](https://user-images.githubusercontent.com/70626250/130573570-ce440648-146f-4993-9492-b58305e7ebff.png)
i tried clearing out space but not even 1.2 gb is enough

**Comment by Tsubajashi** [comment]
you definitely need more than 1.2gb to actually use the software anyway, can you try cleaning your drive up more, to see where the "actual" limit is?

**Comment by n00mkrad** [comment]
1.2gb is nothing lol
