### ISSUE TITLE
Unstable Download Channel

### ISSUE THREAD

**Issue by nvxarm** [n00mkrad/flowframes#77]
Either the shared drive mentioned in README, or the embedded function of update, is unstable.

Why not the official release channel provided by GitHub?

No need for the paid version. It is good enough to put just the free version there.

**Comment by n00mkrad** [comment]
Filesize too big, and no options for a flexible installer (e.g. Pytorch is not needed for AMD users).

**Comment by n00mkrad** [comment]
I'm also not sure what you are referring to, there is no drive in the readme nor an embedded updater.

**Comment by n00mkrad** [comment]
GitHub or GDrive are not an option, they have traffic caps or don't provide direct links.
