### ISSUE TITLE
Remove Duplicate Frames doesn't removes Duplicate Frames

### ISSUE THREAD

**Issue by semel1** [n00mkrad/flowframes#8]
"Remove Duplicate Frames" doesn't remove duplicated frames, but adds more and more duplicated frames with unpredictable insertion pattern producing weird video stream as you increase the threshold value. 
Here the original 23.976fps progressive source with duplicated frames:
https://user-images.githubusercontent.com/53234248/102701727-be9f0500-420e-11eb-9487-09dbc9ab4614.mp4
Here the processed stream with Threshold value = 2%
 https://user-images.githubusercontent.com/53234248/102701757-281f1380-420f-11eb-872c-14f74b803b31.mp4
Here the processed stream with Threshold value = 5%
https://user-images.githubusercontent.com/53234248/102701866-8a2c4880-4210-11eb-8879-ca49340abadb.mp4
Using "frame by frame" clearly demonstrates that inconsistency.

**Comment by n00mkrad** [comment]
Did you use RIFE-NCNN?

**Comment by semel1** [comment]
I used RIFE-CUDA.

**Comment by n00mkrad** [comment]
Cannot reproduce on latest version.


https://user-images.githubusercontent.com/61149547/103083213-24f3a100-45dc-11eb-90eb-cecb43ae2cce.mp4

**Comment by semel1** [comment]
It looks like there is a misunderstanding of the subject of discussion.
As per definition - "remove duplicated frames" clearly means "REMOVE" (this is unambiguous interpretation), and replace them by INTERPOLATED ones. This is my assumption. Or I'm wrong? In my original sample and in your result all duplicates stay in the same places (more or less) instead to be replaced by new interpolated ones. Beside of that length of  you sample - 3s 823ms while the length of the original 4s 213ms. So, the measurement error is ~ 9.26%. It means that "real life"processed video will be completely out of sync.

**Comment by n00mkrad** [comment]
> It looks like there is a misunderstanding of the subject of discussion.
> As per definition - "remove duplicated frames" clearly means "REMOVE" (this is unambiguous interpretation), and replace them by INTERPOLATED ones. This is my assumption. Or I'm wrong? In my original sample and in your result all duplicates stay in the same places (more or less) instead to be replaced by new interpolated ones. Beside of that length of you sample - 3s 823ms while the length of the original 4s 213ms. So, the measurement error is ~ 9.26%. It means that "real life"processed video will be completely out of sync.

I can't quite follow you.

I disabled looping (the above sample was looped once) to verify the length.

Original:
https://user-images.githubusercontent.com/61149547/103091385-46f91d80-45f4-11eb-9644-81eab4f68a50.mp4

4x RIFE, with de-duplication:
https://user-images.githubusercontent.com/61149547/103091386-48c2e100-45f4-11eb-9f3e-cc8e3a168c31.mp4

Length of original: `0:00:01.908000` - Length of interpolation: `0:00:01.908000`.

"Remove duplicated frames" means that identical consecutive input frames will be deleted to avoid a choppy interpolation.

**Comment by semel1** [comment]
1. Sorry, my fault - I compared wrong videos: your looped sample with my wrong version.

2. ""Remove duplicated frames" means that identical consecutive input frames will be deleted to avoid a choppy interpolation." - then why they didn't get deleted and still stays in your "4x RIFE, with de-duplication". Just use "frame advance" with any "frame accurate" video app (Adobe Premiere, VirtualDub2, ...etc.) and you will clearly notice that.

**Comment by n00mkrad** [comment]
> 2. ""Remove duplicated frames" means that identical consecutive input frames will be deleted to avoid a choppy interpolation." - then why they didn't get deleted and still stays in your "4x RIFE, with de-duplication". Just use "frame advance" with any "frame accurate" video app (Adobe Premiere, VirtualDub2, ...etc.) and you will clearly notice that.

They get re-duplicated (extended) to avoid speeding up the output video.

**Comment by RAGEdemon** [comment]
> 
> 
> > 1. ""Remove duplicated frames" means that identical consecutive input frames will be deleted to avoid a choppy interpolation." - then why they didn't get deleted and still stays in your "4x RIFE, with de-duplication". Just use "frame advance" with any "frame accurate" video app (Adobe Premiere, VirtualDub2, ...etc.) and you will clearly notice that.
> 
> They get re-duplicated (extended) to avoid speeding up the output video.

This is clearly wrong. This is a cornerstone topic and should not be closed.

Duplicate frames should NOT get removed and duplicated. They should be removed and then replaced by Interpolated frames. That is the expected behaviour. This is how you avoid "speeding up the output video" and removing stutter in the video.

I am really disheartened that the "owner" is not cognisant of this overarching feature for animated content.

e.g. in an animation, 
The video frames as encoded by codec:
1-2-3-4-5-6-7-8-9

The animated frames (animation frames use a lot of arbitrary duplication and are low FPS in general):
1-1-1-4-4-6-6-6-9

Expected FlowFrames output with interpolation:
1. Remove the duplicate frames and keep time stamp:
1-a-b-4-c-6-d-e-9

2. Interpolate frames a,b,c,d,e from the available frames 1,4,6,9 taking into account time stamps.
Interpolated frames(i): 2i, 3i, 5i, 7i, 8i

3. Integrate and encode video with interpolated frames:
1-2i-3i-4-5i-6-7i-8i-9

When played in a media player, the video will now go from:
1-1-1-4-4-6-6-6-9
to
1-2-3-4-5-6-7-8-9

DAIN tried to do exactly this and it worked quite well, but it took a long time - 3 hours for a 5 minute clip.

Please re-open this, thank you.

**Comment by semel1** [comment]
"Duplicate frames should NOT get removed and then re-duplicated. They should be removed and then replaced by Interpolated frames between the previous frame and the next frame. That is the expected behaviour. This is how you /correctly/ avoid "speeding up the output video" and removing stutter in the video." - totally agree. 

That's exactly what I tried to deliver a while ago.

Of course such approach requires to "fire RIFE/FLAVR/...etc" on each detected dup(s), however it worth it (IMHO),
beside of the fact that it could be "optional" activated at the user's discretion .

The proposed model (just for refreshing) as follow:

Step 1: Performing interpolation detected "dups" only!!! and replacing "dups" in the original source by interpolated ones.
Thus we've got the copy of the original source, but without "dups".

Step2: Performing "final" interpolation of the "truly"  de-dupped  source with a given  interpolation factor.

**Comment by n00mkrad** [comment]
RIFE can only interpolate a pair of two images, generating one synthetic frame.

That's why it's not possible to fill, for example, a gap of two duplicates with two interpolated frames, as RIFE can only create 1, 3, 4 or 7 new frames.

**Comment by semel1** [comment]
At least for one dup (that the most often). For more than one dup (let's say 2 consecutive) you can create 3 and subtract 2nd, and so on .... .

**Comment by Katzenwerfer** [comment]
I know it is certainly possible to have all dupes replaced, but it can be bad for quality in some cases.

**Comment by semel1** [comment]
"...it can be bad for quality in some cases" - that's why - "at the user's discretion in each particular case"
