### ISSUE TITLE
Changing output folder reverts when using batch queue

### ISSUE THREAD

**Issue by curya** [n00mkrad/flowframes#83]
Steps to reproduce:
1. Make sure you have a custom folder selected for output in settings.
2. Add video to flowframes.
3. Change output folder in Interpolation tab.
4. Add to batch queue.
5. Add more files to batch queue
6. Start queue.
7. All files will go to the custom folder selected in settings and NOT to the folder you changed it to in the Interpolation tab.

**Comment by n00mkrad** [comment]
I see, I'll take a look at this.

**Comment by n00mkrad** [comment]
Fixed: https://github.com/n00mkrad/flowframes/commit/659332dd0fe54d4fb7dcf243f1f4757cbbf8b367
