### ISSUE TITLE
Bug Edgecase: unsorted filesystem

### ISSUE THREAD

**Issue by Toastyice** [n00mkrad/flowframes#9]
My Filesystem doesn't sort by name. Which means the frame import mixes up the frames. 
![ddd](https://user-images.githubusercontent.com/26774170/102774197-d3a0a300-438a-11eb-97cc-a897e3392f1b.JPG)
Left Picture -> latest git -> added array sort for the img import, Right -> Patreon 1.9.0 release
I'm most likely the only one with this problem but it's worth fixing anyway.
Proposed change: [https://pastebin.com/StMVCDmf](url)

**Comment by n00mkrad** [comment]
Fixed - Will be included in next commit and 1.19.1
