### ISSUE TITLE
Batch mode?

### ISSUE THREAD

**Issue by deinlandel** [n00mkrad/flowframes#93]
Hello, and thank you for your hard work.

Please consider adding batch mode, selecting every video from a set of small videos is very inconvenient. For example, multiselect videos or ability to select a directory.

**Comment by DestroyTargetNonBasicLand** [comment]
![960983110576951298_DVYZCoxX0AM-97z](https://user-images.githubusercontent.com/36361031/147673547-f700b7ac-d946-4f03-afb7-7db1cb7b6ae0.jpg)

**Comment by n00mkrad** [comment]
> Hello, and thank you for your hard work.
> 
> Please consider adding batch mode, selecting every video from a set of small videos is very inconvenient. For example, multiselect videos or ability to select a directory.

There is a batch mode, drag and drop multiple videos into Flowframes.

**Comment by deinlandel** [comment]
Okay, thank you, but it would be great to make it more obvious, for example allow selecting multiple videos in regular video picker.
